spin_manifest_version = "1"
authors = ["Radu Matei <radu.matei@fermyon.com>"]
description = "A Spin application that translates English to the Belter language from The Expanse."
name = "belter-translator"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
id = "web"
files = [{ source = "web", destination = "/" }]
[component.trigger]
route = "/..."

[[component]]
id = "api"
source = "api/target/spin-http-js.wasm"
allowed_http_hosts = ["https://api.openai.com"]
key_value_stores = ["default"]
[component.trigger]
route = "/api/..."
[component.build]
command = "npm run build"
workdir = "api"


# Spin KV explorer component
[[component]]
source = { url = "https://github.com/radu-matei/spin-kv-explorer/releases/download/v0.6.0/spin-kv-explorer.wasm", digest = "sha256:38110bc277a393cdfb1a885a0fd56923d47314b2086399d1e3bbcb6daa1f04ad" }
id = "kv-explorer"
# add or remove stores you want to explore here
key_value_stores = ["default"]
[component.trigger]
route = "/internal/kv-explorer/..."
